{
  "name": "All",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "test": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "checkout",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "build",
          "run": "dotnet build"
        }
      ]
    },
    "release": {
      "name": "Build and Release",
      "needs": "test",
      "if": "github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "checkout",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "build",
          "run": "pwsh -f ./build.ps1 -release && cd bin && 7z a ../Dotenv.zip Dotenv && cd -"
        },
        {
          "name": "create github release",
          "env": {
            "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
          },
          "run": "gh release create ${{ github.ref_name }} Dotenv.zip --generate-notes --title ${{ github.ref_name }}"
        }
      ]
    }
  }
}
